apiVersion: apps/v1
kind: Deployment
metadata:
  name: oran-nssmf
  labels:
    app: nssmf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nssmf
  template:
    metadata:
      labels:
        app: nssmf
    spec:
      initContainers:
      - name: wait-mariadb
        image: busybox:1.28
        command: ['sh', '-c', 'echo -e "Checking for the availability of Mariadb Server deployment"; while ! nc -z mariadb.default 3306; do sleep 1; printf "-"; done; echo -e "  >> MariaDB Server has started";']
      containers:
      - name: nssmf
        image: registry.gitlab.com/nctuwinlab/o-ran-smo-onos/nssmf-of-ran:latest
        command: ["./nssmf"]
        args: ["-c", "config"]
        ports:
        - containerPort: 30101
        volumeMounts:
        - name: config
          mountPath: "/app/config/nssmf.env"
          subPath: "nssmf.env"
          #readOnly: true
      # access to private registry
      imagePullSecrets:
      - name: winlab-reg-smo-onos
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: nssmf-cfg
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "nssmf.env"
            path: "nssmf.env"
