apiVersion: v1
kind: Service
metadata:
  name: oran-nssmf
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nssmf
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30101
