apiVersion: v1
kind: Service
metadata:
  name: oran-nssmf
spec:
  type: NodePort
  selector:
    app: nssmf
  ports:
    - protocol: TCP
      port: 30101
      targetPort: 30101
      nodePort: 30101
